name: MoveFiles application CI/CD

on:
  push:
    branches: 
      - master
    tags: 
      - 'v*.*.*'
  pull_request: 
    branches:
      - master

jobs:
  build-and-release:
    if: github.event_name == 'push'
    name: MoveFiles application CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Install dependencies
        run: |
          cd src/MoveFiles.Main
          dotnet restore

      - name: Build
        run: |
          cd src/MoveFiles.Main
          dotnet build --configuration Release --no-restore

      - name: Publish Release
        run: |
          cd src/MoveFiles.Main
          dotnet publish -r win-x64 -c Release /p:PublishTrimmed=true -o ../deploy

      - name: Zip Release
        ## You may pin to the exact commit or the version.
        # uses: TheDoctor0/zip-release@a1afcab9c664c9976ac398fa831eac67bed1eb0e
        uses: TheDoctor0/zip-release@0.4.1
        with:
          # Filename for archive
          filename: MoveFiles.zip
          # Base path for archive files
          path: ./src/deploy/
          # Working directory before zipping
          directory: .
          # List of excluded files / directories
          #exclusions: .
          # Tool to use for archiving
          type: zip

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:          
          tag_name: 0.4
          release_name: Release 0.0.4
          prerelease: true
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./MoveFiles.zip
          asset_name: MoveFiles.zip
          asset_content_type: application/zip
